WIP: 6-Translation-Mechanism
jhculb/Coding_Challenge pull request #10
Opened 2022-02-21 22:24 UTC by jhculb

WIP: no work

2022-02-23 08:49 UTC, dachafra requested changes
Take into account the two main comments from the other PR:

1. For RML-reified you CANNOT use `rml:quotedTriplesMap` as they are plain are mappings (you have to follow the standard spec https://rml.io/specs/rml/)
2. You have to take a look at RML-star spec to understand how `rml:NonAssertTriplesMap` works as there are TriplesMap that will need this annotation (https://w3id.org/kg-construct/rml-star)

2022-02-23 08:49 UTC, dachafra commented on src/rml-reified/nested-1.ttl
> +            rml:quotedTriplesMap :firstTM
this is not correct!

2022-02-23 08:49 UTC, dachafra commented on src/rml-reified/nested-1.ttl
> +            rml:quotedTriplesMap :firstTM
You cannot use `quotedTriplesMap` in RML reified mappings, as they are plan RML (you have to follow the standard spec https://rml.io/specs/rml/)

2022-02-23 12:37 UTC, jhculb commented on src/rml-reified/nested-1.ttl
> +            rml:quotedTriplesMap :firstTM
These changes should have been merged in from branch 4 and 5

2022-02-23 12:39 UTC, dachafra approved these changes
As I think here we only have some syntax problems, they should be merged

2022-02-23 12:46 UTC, jhculb commented
> As I think here we only have some syntax problems, they should be merged

Hi @dachafra, this branch was intended to focus on developing the translation mechanism (so this would be the primary development branch until the end of the challenge). I was hoping to do a final merge to main once I had everything sorted and working. 

Which syntax errors have you spotted?

2022-02-23 12:50 UTC, dachafra commented
Maybe I was a bit confused with some comments from yesterday that said to us to review in 6, forget it ;-)

2022-02-23 13:06 UTC, jhculb commented
So I believe that tasks 3 and 5 were agreed complete on this list, could you check 4 is also complete please? :)

- [ ] 3 RDF reification statements
- [ ] 4 RML-star mappings
- [ ] 5 RML reification statements
- [ ] 6 Translation mechanism

I am working on the translation mechanism with the assumption that tasks 3, 4 & 5 are complete until further notice.

2022-02-24 11:11 UTC, merged

2022-02-24 12:36 UTC, jhculb commented
Another case of github merging two branches by accident