4-RML-Star-Mappings
jhculb/Coding_Challenge pull request #8
Opened 2022-02-21 22:10 UTC by jhculb

Not ready for merge.

This mapping would I think parse based on paper374. 
This also feels like a manual effort to define these, rather than an automated one.
I need to check the typing (e.g. whether rml:TriplesMap or rml:NonAssertedTriplesMap, or other datatypes I haven't found yet are more appropriate.)
I also need to find a guide to parsing (I am confident for example the URI :rr and :rml are not written in this format)

2022-02-22 19:12 UTC, jhculb commented
Todo: Find correct URI for rml prefix

2022-02-22 19:18 UTC, dachafra approved these changes

2022-02-22 19:19 UTC, dachafra commented
RDF is `http://www.w3.org/1999/02/22-rdf-syntax-ns#` ;-)

2022-02-22 20:57 UTC, jhculb commented
Ready for review and then merge if no comments @andimou @dachafra

2022-02-22 21:51 UTC, dachafra requested changes
Review the concept of "NonAssertedTriplesMap", the rest is perfect!

2022-02-22 21:51 UTC, dachafra commented on src/rml-star-mappings/syntax-2.rml
> +            rml:quotedTriplesMap :firstTM
this is not correct, the quotedTriplesMap should be in the object (line 20), and here you generated a `rml:NonAssertedTriplesMap` with "s,p,o" values

2022-02-22 21:51 UTC, dachafra commented on src/rml-star-mappings/syntax-3.rml
> +:secondTM a rml:TriplesMap ;
be careful, this is thirdTM not second

2022-02-22 21:51 UTC, dachafra commented on src/rml-star-mappings/syntax-3.rml
> +:firstTM a rml:TriplesMap ;
here firstTM and thirdTM are as well `rml:NonAssertedTriplesMap`
see:
<img width="616" alt="image" src="https://user-images.githubusercontent.com/12400271/155225029-b6f02a7e-a7a8-46dd-8f07-b2d542b0b488.png">

2022-02-22 21:51 UTC, dachafra commented on src/rml-star-mappings/nested-1.rml
> +            rml:reference "c7"
semicolon at the end?

2022-02-22 22:48 UTC, jhculb commented on src/rml-star-mappings/nested-1.rml
> +            rml:reference "c7"
Taken care of in branch 6-

2022-02-23 09:27 UTC, jhculb commented on src/rml-star-mappings/syntax-3.rml
> +:firstTM a rml:TriplesMap ;
Ah I think I see: the csv is saying s1 p1 o1, and we're quoting it. For TriplesMaps we are following the ontology and saying "these triples are linked"?

Regardless, to fix (and I'll copy through all the rest) where it is "s, p, o" and not "<another triple> p o" (or rearrangement) I'll use NonAssertedTriplesMap. Is that accurate?

2022-02-23 09:30 UTC, jhculb commented on src/rml-star-mappings/syntax-3.rml
> +:secondTM a rml:TriplesMap ;
Nice spot, thank you!

2022-02-23 09:31 UTC, jhculb commented on src/rml-star-mappings/syntax-2.rml
> +            rml:quotedTriplesMap :firstTM
Yes, sloppy work here. Thanks for the spot!

2022-02-23 09:36 UTC, jhculb commented on src/rml-star-mappings/syntax-3.rml
> +:firstTM a rml:TriplesMap ;
Ah that's clear now, thank you

2022-02-23 09:50 UTC, jhculb commented on src/rml-star-mappings/syntax-3.rml
> +:firstTM a rml:TriplesMap ;
And to confirm, << <s> <p> <o> >> <p> <q>
The x=<<<s><p><o>>> triple is nonAsserted
But x <p> <q> is just a triplesMap

2022-02-23 11:45 UTC, dachafra requested changes
Review syntax5 I think that "internal-join" TriplesMap should be NonAsserted as well
![image](https://user-images.githubusercontent.com/12400271/155313239-0c1f2c37-a926-4a03-8ed3-e3fd6e6c83f5.png)

2022-02-23 11:45 UTC, dachafra commented on src/rml-star-mappings/syntax-5.ttl
> +:firstJoinTM a rml:TriplesMap ;
I think this is also NonAsserted, right?

2022-02-23 11:45 UTC, dachafra commented on src/rml-star-mappings/syntax-5.ttl
> +:secondJoinTM a rml:TriplesMap ;
I think this is also NonAsserted, right?

2022-02-23 11:51 UTC, jhculb commented on src/rml-star-mappings/syntax-5.ttl
> +:secondJoinTM a rml:TriplesMap ;
Yes to both, the only assertion is the one with the q2 predicate :) Fixing now

2022-02-23 11:52 UTC, jhculb commented
> Review syntax5 I think that "internal-join" TriplesMap should be NonAsserted as well ![image](https://user-images.githubusercontent.com/12400271/155313239-0c1f2c37-a926-4a03-8ed3-e3fd6e6c83f5.png)

Thanks for the spot!

2022-02-23 12:31 UTC, merged