5-RML-Reification-Statements
jhculb/Coding_Challenge pull request #9
Opened 2022-02-21 22:22 UTC by jhculb

WIP: No work

2022-02-22 19:22 UTC, dachafra commented on src/rml-reified/bnode-1.rml
> +    4
ups, and this 4?

2022-02-22 19:22 UTC, dachafra commented on src/rml-reified/bnode-1.rml
> +        rr:reference "myFirstVariable" ;
@andimou how do we manage this? As we shouldn't have this reference for the reification standard blank node in the data... Is there any automatic generation for BN in RML?

2022-02-22 19:44 UTC, jhculb commented on src/rml-reified/bnode-1.rml
> +    4
spolling mistake

2022-02-22 21:30 UTC, jhculb commented
Good evening @dachafra @andimou, hope you are well. Could you review and approve the merge when you are next free please!

2022-02-22 21:31 UTC, jhculb commented on src/rml-reified/nested-1.ttl
> +@prefix xsd: <http://www.w3.org/2001/XMLSchema#>
I realise these are extraneous prefixes. I assume it's fine keeping them around

2022-02-22 21:53 UTC, dachafra commented on src/rml-reified/nested-1.ttl
> +@prefix xsd: <http://www.w3.org/2001/XMLSchema#>
this is good!

2022-02-22 21:56 UTC, dachafra requested changes
You cannot use rml:quotedTriplesMaps in plan RDF, you may need to take a look to RML spec to see how you can do it (maybe just repeating some rules...)

2022-02-22 21:56 UTC, dachafra commented on src/rml-reified/syntax-2.ttl
> +
did you validate this RDF? I think you need a `.` at the end

2022-02-22 21:56 UTC, dachafra commented on src/rml-reified/syntax-2.ttl
> +
review in the rest please

2022-02-22 21:56 UTC, dachafra commented on src/rml-reified/syntax-3.ttl
> +            rml:quotedTriplesMap :elementaryTM1
NO! You cannot use this in plan RML, there should be another way ;-)

2022-02-22 21:56 UTC, dachafra commented on src/rml-reified/syntax-3.ttl
> +            rml:quotedTriplesMap :elementaryTM2
again, this is not good

2022-02-22 21:56 UTC, dachafra commented on src/rml-reified/syntax-4.ttl
> +            rml:quotedTriplesMap :elementaryTM2
again, we cannot use this!

2022-02-22 22:49 UTC, jhculb commented on src/rml-reified/syntax-2.ttl
> +
> did you validate this RDF? I think you need a `.` at the end

I did when parsing the triples as part of 6.

2022-02-23 10:13 UTC, jhculb commented
> You cannot use rml:quotedTriplesMaps in plan RDF, you may need to take a look to RML spec to see how you can do it (maybe just repeating some rules...)

Are you referring to parentTriplesMap? This seems to be how to map two logical sources (csvs, etc.) together?

(currently reading R2RML spec to see if I've missed something there)

2022-02-23 10:15 UTC, dachafra commented
It could be a good option, yes ;-)

2022-02-23 10:53 UTC, jhculb commented
> It could be a good option, yes ;-)

So I think it is a direct replacement in all occurences in these examples, though reading the rml.io specs was a little unclear about parent and children, and I feel I may have trippled up here.

Could you give this a review please as I think I have addressed your comments?

2022-02-23 12:20 UTC, dachafra commented
If the source of the parentTriplesMap and the actual TriplesMap is the same, you do not need to put a join-condition

2022-02-23 12:22 UTC, dachafra approved these changes
ready to merge

2022-02-23 12:31 UTC, merged